[workspace]
resolver = "2"
members = ["py-bindings", "rpc", "sim"]


[workspace.dependencies]
foundry-evm = { git = "https://github.com/foundry-rs/foundry", tag = "nightly-e649e62f125244a3ef116be25dfdc81a2afbaf2a", features = [
] }
alloy = { version = "0.5.4", features = ["full"] }
anyhow = "1.0.95" # Flexible concrete Error type built on std::error::Error
serde = "1.0.217" # A generic serialization/deserialization framework
hex = "0.4.3"                        # Encoding and decoding data into/from hexadecimal representation.
serde_json = "1.0.135"                                 # A JSON serialization file format
pyo3-stub-gen = "0.7.0"
smol = "2.0.2"                     # A small and fast async runtime
tonic = "0.12.3"                  # A gRPC over HTTP/2 implementation focused on high performance, interoperability, and flexibil…
prost = "0.13"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
tonic-build = "0.12.3"                   # Codegen module of `tonic` gRPC implementation. 
log = "0.4.26"                             # A lightweight logging facade for Rust 
ethers = "2.0.14"                    # A complete Ethereum and Celo Rust library