[package]
name = "py-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { workspace = true }
sim = { path = "../sim" }
anyhow = { workspace = true }
hex = { workspace = true }

[lib]
name = "evm_simulator"