# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from enum import Enum, auto

class DatabaseErrorRef:
    def get(self) -> builtins.str:
        ...


class EvmExecutionError:
    ...

class EvmExecutionResult:
    ...

class EvmSimulator:
    def __new__(cls,url:builtins.str): ...
    def simulate(self, transactions:Txs) -> builtins.list[SimulationResult]:
        ...


class Transaction:
    def __new__(cls,_from:builtins.str, to:builtins.str, value:builtins.str, data:typing.Sequence[builtins.int]): ...
    ...

class Txs:
    def __new__(cls,txs:typing.Sequence[Transaction]): ...
    ...

class SimulationResult(Enum):
    Ok = auto()
    Err = auto()

