# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class EvmSimulator:
    ...

class Transaction:
    ...

class Txs:
    def __new__(cls,txs:typing.Sequence[Transaction]): ...
    ...

