[package]
name = "simulator-core"
version = "0.1.0"
edition = "2021"

[dependencies]
foundry-evm = { workspace = true }
tokio = { workspace = true }
alloy = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }